name: Update issues on PR close

on:
  pull_request:
    types:
      - closed

jobs:
  run:
    name: "Mark issues done"
    runs-on: ubuntu-latest
    steps:
      - name: Update Labels
        uses: RebeccaStevens/issue-closed-labeler-action@latest
        with:
          rules: '[{"add": "Done"}]'
